# Generated by Django 5.1.6 on 2025-03-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
