# Generated by Django 5.1.6 on 2025-03-08 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_inscription_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='inscription',
            old_name='first_name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='inscription',
            old_name='num_places',
            new_name='nombre_de_places',
        ),
        migrations.RenameField(
            model_name='inscription',
            old_name='last_name',
            new_name='prénom',
        ),
    ]
