# Generated by Django 5.1.6 on 2025-03-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_name_event_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(default=50),
        ),
    ]
